name: runoff-webgis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - python-multipart
  - geopandas
  - rasterio
  - fiona
  - shapely
  - pyproj
  - pandas
  - numpy
  - pytest
  - nodejs
