name: geoproject
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - numpy
  - plotly
  - streamlit
  - pydeck
  - pyyaml
  - pytest
  - pillow
