"""Atomic figure: response-unit CN-adjustment map.

Shows where the response-unit curve-number adjustment is applied. The
separate area-summary bar chart is generated by
``fig04_response_unit_cn_adjustment.py`` so each figure has one visual task.
"""
from __future__ import annotations
from pathlib import Path
import sys; sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

from scripts.figures.lib.figure_style import (
    apply_style,
    save_atomic_figure,
    C_UPPER,
)
from scripts.figures.lib.io import load_vector, LATEX, WORKING_CRS, PROCESSED

OUT = LATEX / "fig03_response_units_map.png"

CN_CLASS_COLORS = {0: "#f7f7f7", 4: "#fdcc8a", 8: "#fc8d59", 12: "#d7301f"}
CN_CLASS_LABELS = {
    0: "0 (unburned, no adjustment)",
    4: "4 (low severity fire)",
    8: "8 (moderate severity fire)",
    12: "12 (high severity, none found)",
}


def classify_cn_delta(units: gpd.GeoDataFrame) -> np.ndarray:
    cn_delta = (
        units["burned_parameter"].fillna(units["baseline_parameter"])
        - units["baseline_parameter"]
    ).to_numpy(float)
    cn_class = np.zeros(len(units), dtype=int)
    cn_class[cn_delta >= 4] = 4
    cn_class[cn_delta >= 8] = 8
    cn_class[cn_delta >= 12] = 12
    return cn_class


def add_scale_bar(ax, length_m: float = 2000.0, n_seg: int = 4) -> None:
    x0, x1 = ax.get_xlim()
    y0, y1 = ax.get_ylim()
    sb_x = x0 + 0.06 * (x1 - x0)
    sb_y = y0 + 0.06 * (y1 - y0)
    for i in range(n_seg):
        color = "black" if i % 2 == 0 else "white"
        ax.add_patch(
            plt.Rectangle(
                (sb_x + i * length_m / n_seg, sb_y),
                length_m / n_seg,
                0.018 * (y1 - y0),
                facecolor=color,
                edgecolor="black",
                linewidth=0.5,
                zorder=11,
            )
        )
    ax.text(
        sb_x + length_m / 2,
        sb_y + 0.024 * (y1 - y0),
        f"{length_m / 1000:g} km",
        ha="center",
        fontsize=7,
        zorder=11,
    )


def main() -> None:
    catchment = load_vector("catchment_utm32", "boundary")
    fire = load_vector("monte_martica_fire_2019_utm32", "fire_perimeter")
    ru_path = PROCESSED / "model_inputs" / "runoff_units.gpkg"
    units = gpd.read_file(ru_path).to_crs(WORKING_CRS)
    cn_class = classify_cn_delta(units)

    apply_style()
    fig, ax = plt.subplots(figsize=(7.4, 6.6))

    for cls_val, color in sorted(CN_CLASS_COLORS.items()):
        mask = cn_class == cls_val
        if mask.any():
            units.loc[mask].plot(
                ax=ax,
                color=color,
                edgecolor="black",
                linewidth=0.25,
                alpha=0.88,
                zorder=6,
                label=CN_CLASS_LABELS[cls_val],
            )

    catchment.plot(
        ax=ax,
        facecolor="none",
        edgecolor="black",
        linewidth=1.3,
        zorder=7,
        label="Candidate subcatchment",
    )
    fire.plot(
        ax=ax,
        facecolor="none",
        edgecolor=C_UPPER,
        linewidth=1.1,
        linestyle="--",
        zorder=8,
        label="Official fire perimeter",
    )

    ax.set_xlabel("Easting (m, UTM Zone 32N)", fontsize=8)
    ax.set_ylabel("Northing (m, UTM Zone 32N)", fontsize=8)
    ax.ticklabel_format(style="plain", useOffset=False)
    add_scale_bar(ax)
    ax.text(
        0.03,
        0.03,
        "EPSG:32632",
        transform=ax.transAxes,
        fontsize=6,
        color="#777777",
        ha="left",
        va="bottom",
    )

    legend_elements = [
        Patch(
            facecolor=CN_CLASS_COLORS[k],
            edgecolor="black",
            linewidth=0.3,
            label=CN_CLASS_LABELS[k],
        )
        for k in [0, 4, 8, 12]
        if (cn_class == k).any()
    ]
    ax.legend(
        handles=legend_elements
        + [
            Line2D([0], [0], color="black", linewidth=1.3, label="Candidate subcatchment"),
            Line2D(
                [0],
                [0],
                color=C_UPPER,
                linewidth=1.1,
                linestyle="--",
                label="Official fire perimeter",
            ),
        ],
        loc="upper left",
        frameon=False,
        fontsize=6.2,
    )

    fig.tight_layout()
    save_atomic_figure(fig, OUT)
    print(f"  -> {OUT}")


if __name__ == "__main__":
    main()
